# Generated by Django 3.2.19 on 2023-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subTitle',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='game',
            name='subgenres',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Survival and horror'), (2, 'Fantasy'), (3, 'Sci-Fi'), (4, 'Action-adventure'), (5, 'Comedy'), (7, 'Cyberpunk'), (8, 'Apocalyptic'), (9, 'MMORPG'), (10, 'Strategy')], default=0),
            preserve_default=False,
        ),
    ]
