# Generated by Django 3.2.19 on 2023-07-04 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230628_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Playstation', 'Playstation'), ('Xbox', 'Xbox'), ('PC', 'PC'), ('VR', 'VR'), ('Nintendo', 'Nintendo')], max_length=31),
        ),
    ]
