# Generated by Django 3.2.19 on 2023-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='subgenres',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'Survival and horror'), (2, 'Fantasy'), (3, 'Sci-Fi'), (5, 'Action-adventure'), (5, 'Comedy'), (7, 'Cyberpunk'), (8, 'Apocalyptic'), (9, 'MMORPG'), (10, 'Strategy')]),
        ),
    ]
